<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1xwyIGp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1xwyIGp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1xwyIGp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1xwyIGp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1xwyIGp\App_KernelDevDebugContainer([
    'container.build_hash' => '1xwyIGp',
    'container.build_id' => 'b81d63db',
    'container.build_time' => 1645916456,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1xwyIGp');
