<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7s8vsX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7s8vsX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM7s8vsX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM7s8vsX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM7s8vsX\App_KernelDevDebugContainer([
    'container.build_hash' => 'M7s8vsX',
    'container.build_id' => 'f62b6ffe',
    'container.build_time' => 1646047034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7s8vsX');
