<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'course' => [[], ['_controller' => 'App\\Controller\\CourseController::course'], [], [['text', '/course']], [], [], []],
    'listCourse' => [[], ['_controller' => 'App\\Controller\\CourseController::listCourse'], [], [['text', '/listC']], [], [], []],
    'subjectRegister' => [[], ['_controller' => 'App\\Controller\\CourseController::subjectRegister'], [], [['text', '/subjectRegister']], [], [], []],
    'listSubject' => [[], ['_controller' => 'App\\Controller\\CourseController::listSubject'], [], [['text', '/listSubject']], [], [], []],
    'addSubject' => [[], ['_controller' => 'App\\Controller\\CourseController::addSubject'], [], [['text', '/addSubject']], [], [], []],
    'courseManually' => [[], ['_controller' => 'App\\Controller\\CourseController::courseManually'], [], [['text', '/course_manually']], [], [], []],
    'subjectManually' => [[], ['_controller' => 'App\\Controller\\CourseController::subjectManually'], [], [['text', '/subject_manually']], [], [], []],
    'asssignManually' => [[], ['_controller' => 'App\\Controller\\CourseController::asssignManually'], [], [['text', '/assign_manually']], [], [], []],
    'listCourseUser' => [[], ['_controller' => 'App\\Controller\\CourseController::listCourseUser'], [], [['text', '/listCourseUser']], [], [], []],
    'listCourseUserManually' => [[], ['_controller' => 'App\\Controller\\CourseController::listCourseUserManually'], [], [['text', '/listCourseUserManually']], [], [], []],
    'assignSubject' => [[], ['_controller' => 'App\\Controller\\CourseController::assignSubject'], [], [['text', '/assignSubject']], [], [], []],
    'listCourseAssign' => [[], ['_controller' => 'App\\Controller\\CourseController::listCourseAssign'], [], [['text', '/listCourseAs']], [], [], []],
    'panel' => [[], ['_controller' => 'App\\Controller\\PanelController::panel'], [], [['text', '/panel']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegistroController::register'], [], [['text', '/register']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\RegistroController::login'], [], [['text', '/']], [], [], []],
    'loginManually' => [[], ['_controller' => 'App\\Controller\\RegistroController::loginManually'], [], [['text', '/login_manually']], [], [], []],
    'registerManually' => [[], ['_controller' => 'App\\Controller\\RegistroController::registerManually'], [], [['text', '/register_manually']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\RegistroController::home'], [], [['text', '/home']], [], [], []],
    'get_all_subjects' => [[], ['_controller' => 'App\\Controller\\SubjectController::getAll'], [], [['text', '/api/subjects']], [], [], []],
    'add_subject' => [[], ['_controller' => 'App\\Controller\\SubjectController::add'], [], [['text', '/api/subject']], [], [], []],
    'delete_subject' => [['id'], ['_controller' => 'App\\Controller\\SubjectController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/subject']], [], [], []],
    'update_subject' => [['id'], ['_controller' => 'App\\Controller\\SubjectController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/subject']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
