<?php

namespace ContainerM7s8vsX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubjectControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SubjectController' shared autowired service.
     *
     * @return \App\Controller\SubjectController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/SubjectController.php';

        return $container->services['App\\Controller\\SubjectController'] = new \App\Controller\SubjectController(($container->services['App\\Repository\\SubjectRepository'] ?? $container->load('getSubjectRepositoryService')));
    }
}
